runtime: go
api_version: go1

handlers:
  - url: /.*
    script: _go_app

env_variables:
  FIREBASE_URL: "https://souschef-182502.firebaseio.com"
  FIREBASE_AUTH_TOKEN: "4maH9UaAtODP5C64FUCpn51Y6kaKSjeSCIHuPZ5y"
  SPOONACULAR_AUTH_TOKEN: "uepxLqZUYVmsh3gwOJ44SxTecjIDp1DZr5ZjsnBLFISjcf2rrH"

#  SPOONACULAR_AUTH_TOKEN: "QFuG20M4Admsh3W47aaSb3J8Eai6p1uuf5zjsnYhFyBiqD8O5i"